name: 'Send DingTalk Message'
description: 'Send message to DingTalk webhook, supports optional signing'
inputs:
  webhook:
    description: 'DingTalk webhook URL'
    required: true
  secret:
    description: 'DingTalk secret key (optional, for signed bots)'
    required: false
  message:
    description: 'Message content to send'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
